version: '3'
services:
  grav:
    build:
      context: .
      args:
        GRAV_VERSION: 1.4.2
        ADMIN_USER: admin
        ADMIN_PASSWORD: 0Gravity
        ADMIN_EMAIL: admin@example.com
        ADMIN_PERMISSIONS: b
        ADMIN_FULLNAME: "Sandra Bullock"
        ADMIN_TITLE: Administrator
        LOCALE_LANGUAGE: ja_JP.UTF-8
        LOCALE_ENCODING: UTF-8
    tty: true
    container_name: grav
    volumes:
      - grav:/var/www/grav/
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    networks:
      - default
    restart: always
volumes:
  grav:
    external: false
